### ISSUE TITLE
hi, the src didn't support recursive directory

### ISSUE THREAD

**Issue by qileilove** [sindresorhus/gulp-plato#11]
hi, the src didn't support recursive directory to find all the js file, when the src menu is below. 
![image](https://cloud.githubusercontent.com/assets/3895501/20745184/0ca67c5c-b71b-11e6-9866-cb8f7cd1963b.png)

**Comment by sindresorhus** [comment]
From the top of the readme:

> Deprecated. Just use plato directly.
